/**
 * Week Replay — synthesized audio engine (no external assets).
 *
 * The sound is meant to be read, not just heard. It follows the brand's own
 * terms: calm, specific, no hype. So it behaves like an instrument the map is
 * playing rather than a soundtrack laid over it —
 *
 * - x on the map is stereo position, y is register, so a dot in the north-west
 *   sounds high and to the left;
 * - pitch comes from the event's category, taken from its position in the
 *   shared color palette, so a category always sounds like itself and the
 *   most common ones sit lowest;
 * - an ambient pad tracks the same night and weekend signals the map washes
 *   itself with, and breathes on the 4-second cycle of the bracket loader;
 * - key moments ring as soft bells, and the week closes on a slow exhale.
 *
 * Three choices do most of the work in keeping it listenable. Voices are soft
 * mallets with long reverberant tails instead of bare sine pips, so overlapping
 * events blur into one texture. Onsets are rate limited, so a busy Tuesday
 * reads as weight and density rather than a burst of clicks. And everything
 * sits in a pentatonic scale, so no ordering of events can produce a dissonance.
 *
 * buildAudioSchedule() is pure and testable without a browser.
 * createReplayAudioEngine() drives a live AudioContext with a rolling
 * lookahead. renderReplayAudio() renders the same schedule offline for the
 * video export, so a shared clip sounds identical to what was on screen.
 */

import {
  SUBCATEGORY_PALETTE,
  nightness,
  weekendness,
  type PlaybackTimeline,
} from "./weekReplay";

// ── Public types ────────────────────────────────────────────────────────────

export interface ReplayAudioEvent {
  /** Playback ms at which the event lands. */
  playMs: number;
  /** Horizontal position as a 0 (west) … 1 (east) fraction of the map. */
  panX: number;
  /** Vertical position as a 0 (north) … 1 (south) fraction of the map. */
  posY: number;
  /** The event's category color, from the shared subcategory palette. */
  color: string;
}

export interface AudioTick {
  /** Playback ms at which this note sounds. */
  playMs: number;
  /** Stereo pan, –1 (left) … +1 (right). */
  panX: number;
  /** Fundamental: the category's seat in the chord currently sounding. */
  freqHz: number;
  /** Relative velocity 0–1; rises with how many events merged into this note. */
  level: number;
  /** Which instrument plays it — one per category. */
  timbre: number;
}

export interface AudioChime {
  playMs: number;
  /** Gold-ring / 311 photo events ring brighter. */
  isPhoto: boolean;
  /** Root of the chord sounding when it fires, so it lands in the harmony. */
  rootHz: number;
}


export interface AudioPadPoint {
  playMs: number;
  nightLevel: number;
  weekendLevel: number;
}

export interface AudioSchedule {
  ticks: AudioTick[];
  chimes: AudioChime[];
  /** Playback duration in ms; the closing swell starts here. */
  endMs: number;
  /** Sampled at PAD_INTERVAL_MS so the pad can be ramped continuously. */
  padPoints: AudioPadPoint[];
}

export interface ReplayAudioEngine {
  /** Begin playback from a position — call in response to a play gesture. */
  start(atPlayMs?: number): void;
  pause(): void;
  seek(playMs: number): void;
  setMuted(muted: boolean): void;
  dispose(): void;
}

// ── Musical material ────────────────────────────────────────────────────────

/** F3. Everything is measured in semitones from here. */
const ROOT_HZ = 174.61;
/** Pad root, an octave below the melodic root. */
const PAD_ROOT_HZ = ROOT_HZ / 2; // F2

const semitones = (n: number) => Math.pow(2, n / 12);

/**
 * The week's chord progression, all drawn from F Dorian.
 *
 * This is what makes the replay read as music rather than as a scale being
 * plucked at: the harmony moves underneath while events arrive in whatever
 * order the week happened. A category holds a fixed seat in each chord, so it
 * keeps its identity but changes pitch as the chords turn — the melody is
 * generated by the data crossing a moving harmony, not composed.
 *
 * Every voice is a degree of one mode, so no chord can clash with the pad and
 * no two events can clash with each other, whatever order they land in.
 */
interface Chord {
  /** Semitones above the root for the pad's bass. */
  bass: number;
  /** One seat per category, ascending. */
  voices: readonly number[];
}

const PROGRESSION: readonly Chord[] = [
  { bass: 0, voices: [0, 3, 7, 10, 14] }, // i     F Ab C Eb G
  { bass: 3, voices: [3, 7, 10, 12, 14] }, // III  Ab C Eb F G
  { bass: 5, voices: [5, 7, 9, 12, 14] }, // IV    Bb C D F G
  { bass: 10, voices: [0, 5, 9, 10, 14] }, // VII  F Bb D Eb G
];

/** Chord changes per replay: the progression turns twice over the week. */
const CHORD_SEGMENTS = PROGRESSION.length * 2;

/** Which chord is sounding at a playback position. */
function chordIndexAt(playMs: number, durationMs: number): number {
  if (!(durationMs > 0)) return 0;
  const segment = Math.floor((playMs / durationMs) * CHORD_SEGMENTS);
  return Math.max(0, Math.min(CHORD_SEGMENTS - 1, segment)) % PROGRESSION.length;
}

/**
 * A category's index in the shared palette, which upstream assigns by
 * descending event count — so index 0 is the busiest category of the week.
 */
function categoryIndex(color: string): number {
  const found = SUBCATEGORY_PALETTE.indexOf(color);
  return found >= 0 ? found : 0;
}

/**
 * Pitch for an event: its category takes a seat in the chord that is currently
 * sounding, and how far north it sits on the map picks the octave.
 */
function eventFreq(color: string, posY: number, chord: Chord): number {
  const index = categoryIndex(color);
  const voice = chord.voices[index % chord.voices.length];
  // Only the map lifts the register. Categories past the fifth seat used to
  // climb an octave to stay distinct, which is no longer needed now that each
  // one has its own instrument — and it kept the top of the range shrill.
  const northLift = posY < 0.45 ? 1 : 0;
  return ROOT_HZ * semitones(voice) * Math.pow(2, northLift);
}

// ── Timbres ─────────────────────────────────────────────────────────────────

/**
 * One voice per category, so a category is recognizable by its color of sound
 * as well as its pitch — the audible counterpart of the metric icons on the map.
 *
 * All of them are additive stacks of sine partials rather than raw waveforms:
 * that is what lets six different voices overlap without turning to mud. They
 * differ in which partials they carry, how fast each partial dies, and how the
 * filter closes, which is where "marimba" versus "glass" actually lives.
 */
interface Timbre {
  name: string;
  /** [frequency ratio, level, decay multiplier] per partial. */
  partials: readonly (readonly [number, number, number])[];
  attack: number;
  /** Base decay in seconds; low notes ring longer (see scheduleVoice). */
  decay: number;
  /** Lowpass sweep, as multiples of the fundamental. */
  filterFrom: number;
  filterTo: number;
  level: number;
}

const TIMBRES: readonly Timbre[] = [
  {
    name: "marimba",
    partials: [
      [1, 1, 1],
      [2, 0.22, 0.55],
      [3.9, 0.06, 0.3],
    ],
    attack: 0.006,
    decay: 0.42,
    filterFrom: 5,
    filterTo: 1.6,
    level: 1,
  },
  {
    name: "glass",
    partials: [
      [1, 1, 1],
      [2.76, 0.28, 0.8],
      [5.4, 0.09, 0.5],
    ],
    attack: 0.014,
    decay: 0.95,
    filterFrom: 7,
    filterTo: 2.5,
    level: 0.82,
  },
  {
    name: "pluck",
    partials: [
      [1, 1, 1],
      [2, 0.38, 0.6],
      [3, 0.16, 0.4],
      [4, 0.07, 0.25],
    ],
    attack: 0.003,
    decay: 0.5,
    filterFrom: 6,
    filterTo: 1.2,
    level: 0.8,
  },
  {
    name: "wood",
    partials: [
      [1, 1, 1],
      [2.3, 0.33, 0.35],
      [4.1, 0.11, 0.2],
    ],
    attack: 0.002,
    decay: 0.24,
    filterFrom: 4,
    filterTo: 1.1,
    level: 0.92,
  },
  {
    name: "reed",
    partials: [
      [1, 1, 1],
      [2, 0.45, 1],
      [3, 0.22, 0.8],
      [5, 0.07, 0.5],
    ],
    attack: 0.055,
    decay: 0.7,
    filterFrom: 3.2,
    filterTo: 1.8,
    level: 0.68,
  },
  {
    name: "chime",
    partials: [
      [1, 1, 1],
      [2.01, 0.4, 0.8],
      [3.01, 0.18, 0.6],
      [4.7, 0.06, 0.35],
    ],
    attack: 0.008,
    decay: 1.25,
    filterFrom: 8,
    filterTo: 3,
    level: 0.66,
  },
];

/** Timbre for a category. Stable, so a category always sounds like itself. */
function timbreIndex(color: string): number {
  return categoryIndex(color) % TIMBRES.length;
}

// ── Schedule builder ────────────────────────────────────────────────────────

/** Events landing within this window become one note. */
const TICK_MERGE_MS = 70;
/**
 * Floor on the gap between notes.
 *
 * Without it, a dense afternoon fires a dozen notes a second and the whole
 * thing turns into a rattle. Skipped events are not silent: they push the
 * surviving note's velocity up, so density is heard as weight instead.
 *
 * Tuned by measuring a realistic week: much above this and most events go
 * unheard, so the track stops tracking the dots landing on the map; much
 * below and dense afternoons clatter.
 */
const MIN_ONSET_GAP_MS = 125;
/** Deterministic jitter added to the floor so capped stretches don't tick. */
const ONSET_JITTER_MS = 35;
/** Ambient pad is sampled this often along the timeline. */
const PAD_INTERVAL_MS = 400;
/** Merged events beyond this count stop adding velocity. */
const LEVEL_SATURATION = 6;

/** Small deterministic PRNG, so live playback and the export agree exactly. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Build an audio schedule from the replay's events and timeline.
 * Pure — no AudioContext required.
 */
export function buildAudioSchedule(
  events: ReplayAudioEvent[],
  keyMoments: Array<{ playStartMs: number; isPhoto: boolean }>,
  timeline: PlaybackTimeline,
): AudioSchedule {
  const sorted = [...events].sort((a, b) => a.playMs - b.playMs);
  const random = mulberry32(sorted.length * 2654435761);
  const ticks: AudioTick[] = [];

  let lastOnset = -Infinity;
  let i = 0;
  while (i < sorted.length) {
    const base = sorted[i];
    let end = i + 1;
    while (end < sorted.length && sorted[end].playMs - base.playMs <= TICK_MERGE_MS) {
      end++;
    }
    const group = sorted.slice(i, end);
    i = end;

    const gap = MIN_ONSET_GAP_MS + random() * ONSET_JITTER_MS;
    if (base.playMs - lastOnset < gap) {
      // Too soon to sound: fold this cluster into the previous note's weight.
      if (ticks.length) {
        const prev = ticks[ticks.length - 1];
        prev.level = Math.min(1, prev.level + group.length / (LEVEL_SATURATION * 2));
      }
      continue;
    }
    lastOnset = base.playMs;

    const avgPan = group.reduce((s, e) => s + e.panX, 0) / group.length;
    const avgY = group.reduce((s, e) => s + e.posY, 0) / group.length;
    const chord = PROGRESSION[chordIndexAt(base.playMs, timeline.durationMs)];
    ticks.push({
      playMs: base.playMs,
      panX: Math.max(-1, Math.min(1, avgPan * 2 - 1)),
      freqHz: eventFreq(base.color, avgY, chord),
      level: Math.min(1, 0.45 + (group.length - 1) / LEVEL_SATURATION),
      timbre: timbreIndex(base.color),
    });
  }

  const chimes: AudioChime[] = keyMoments.map((m) => ({
    playMs: m.playStartMs,
    isPhoto: m.isPhoto,
    rootHz:
      ROOT_HZ *
      semitones(
        PROGRESSION[chordIndexAt(m.playStartMs, timeline.durationMs)].bass,
      ),
  }));

  const padPoints: AudioPadPoint[] = [];
  for (let ms = 0; ms <= timeline.durationMs + PAD_INTERVAL_MS; ms += PAD_INTERVAL_MS) {
    const clamped = Math.min(ms, timeline.durationMs);
    const weekMs = timeline.weekTimeAt(clamped);
    padPoints.push({
      playMs: clamped,
      nightLevel: nightness(weekMs),
      weekendLevel: weekendness(weekMs),
    });
    if (ms >= timeline.durationMs) break;
  }

  return { ticks, chimes, endMs: timeline.durationMs, padPoints };
}

// ── Space ───────────────────────────────────────────────────────────────────

type AnyContext = AudioContext | OfflineAudioContext;

/** Reverb tail length. Long enough that sparse notes still feel connected. */
const REVERB_SECONDS = 2.6;
const REVERB_DECAY = 2.4;

/**
 * Plate-ish reverb from a synthesized impulse response.
 *
 * This is the difference between "pips" and "a room". Exponentially decaying
 * noise, low-passed so the tail is dark rather than hissy, generated from a
 * fixed seed so every render is identical.
 */
function createReverb(ctx: AnyContext): ConvolverNode {
  const rate = ctx.sampleRate;
  const length = Math.max(1, Math.floor(rate * REVERB_SECONDS));
  const impulse = ctx.createBuffer(2, length, rate);
  const random = mulberry32(0x5eed);
  for (let channel = 0; channel < 2; channel++) {
    const data = impulse.getChannelData(channel);
    let previous = 0;
    for (let n = 0; n < length; n++) {
      const t = n / length;
      const white = random() * 2 - 1;
      // One-pole lowpass on the noise darkens the tail.
      previous = previous * 0.72 + white * 0.28;
      data[n] = previous * Math.pow(1 - t, REVERB_DECAY);
    }
  }
  const convolver = ctx.createConvolver();
  convolver.buffer = impulse;
  return convolver;
}

interface Bus {
  /**
   * Stable input for struck voices, already sending to the reverb. Live
   * playback hangs a disposable gain off this per generation, so stopping a
   * replay never has to rewire the reverb.
   */
  voiceIn: GainNode;
  /** Pad input; kept drier so it stays a bed rather than a wash. */
  pad: GainNode;
  master: GainNode;
}

/**
 * Master chain: voices and pad into a shared reverb, then gentle compression.
 *
 * The high-shelf cut and the 48 Hz high-pass are both about laptop speakers,
 * where untamed highs sound brittle and sub-bass just eats headroom.
 */
function createBus(ctx: AnyContext, masterLevel: number): Bus {
  const master = ctx.createGain();
  master.gain.value = masterLevel;

  const softener = ctx.createBiquadFilter();
  softener.type = "highshelf";
  softener.frequency.value = 6000;
  softener.gain.value = -4;

  const rumbleCut = ctx.createBiquadFilter();
  rumbleCut.type = "highpass";
  rumbleCut.frequency.value = 48;

  const compressor = ctx.createDynamicsCompressor();
  compressor.threshold.value = -22;
  compressor.knee.value = 26;
  compressor.ratio.value = 2.5;
  compressor.attack.value = 0.012;
  compressor.release.value = 0.28;

  /**
   * Make-up gain, after the compressor rather than before it.
   *
   * Individual voices are deliberately quiet so dozens can overlap without
   * clipping, which leaves the sum far too quiet next to anything else the
   * viewer is listening to. Lifting here rather than at the source keeps the
   * compressor seeing the same signal, so the dynamics don't change with it.
   */
  const makeUp = ctx.createGain();
  makeUp.gain.value = 2.5;

  master.connect(softener);
  softener.connect(rumbleCut);
  rumbleCut.connect(compressor);
  compressor.connect(makeUp);
  makeUp.connect(ctx.destination);

  const reverb = createReverb(ctx);
  const wet = ctx.createGain();
  wet.gain.value = 0.9;
  reverb.connect(wet);
  wet.connect(master);

  const voiceIn = ctx.createGain();
  voiceIn.gain.value = 1;
  voiceIn.connect(master);
  const voiceSend = ctx.createGain();
  voiceSend.gain.value = 0.42;
  voiceIn.connect(voiceSend);
  voiceSend.connect(reverb);

  const pad = ctx.createGain();
  pad.gain.value = 1;
  pad.connect(master);
  const padSend = ctx.createGain();
  // Barely wet. A drone with much reverb on it stops being a floor and starts
  // being a wash, which is the other half of sounding grating.
  padSend.gain.value = 0.08;
  pad.connect(padSend);
  padSend.connect(reverb);

  return { voiceIn, pad, master };
}

// ── Voices ──────────────────────────────────────────────────────────────────

/** Hard pans collapse on speakers and fatigue on headphones. */
const PAN_WIDTH = 0.72;

/**
 * Play one note on one of the TIMBRES.
 *
 * Each partial gets its own envelope, which is the difference between an
 * instrument and a beep: the upper partials die faster than the fundamental,
 * so a note starts bright and settles, the way a struck or plucked thing does.
 * A filter closing over the same span does the rest.
 */
function scheduleVoice(
  ctx: AnyContext,
  dest: AudioNode,
  at: number,
  freqHz: number,
  panX: number,
  level: number,
  timbre: Timbre,
  detune: number,
): void {
  // Quieter as it climbs, so high notes read as distant rather than piercing.
  const brightnessTrim = 1 - 0.35 * Math.min(1, freqHz / 1200);
  const peak = 0.064 * timbre.level * (0.55 + level * 0.45) * brightnessTrim;
  // Low notes ring longer, as they do on any real resonator.
  const decay = timbre.decay * (0.75 + 220 / freqHz);

  const panner = ctx.createStereoPanner();
  panner.pan.value = Math.max(-1, Math.min(1, panX)) * PAN_WIDTH;
  panner.connect(dest);

  const tone = ctx.createBiquadFilter();
  tone.type = "lowpass";
  tone.Q.value = 0.7;
  tone.frequency.setValueAtTime(
    Math.min(11000, freqHz * timbre.filterFrom),
    at,
  );
  tone.frequency.exponentialRampToValueAtTime(
    Math.max(180, freqHz * timbre.filterTo),
    at + decay * 0.8,
  );
  tone.connect(panner);

  for (const [ratio, partialLevel, decayScale] of timbre.partials) {
    const osc = ctx.createOscillator();
    osc.type = "sine";
    // A few cents of detune per note keeps repeats from sounding machined.
    osc.frequency.value = freqHz * ratio * (1 + detune);

    const env = ctx.createGain();
    const partialDecay = Math.max(0.05, decay * decayScale);
    env.gain.setValueAtTime(0.0001, at);
    env.gain.linearRampToValueAtTime(peak * partialLevel, at + timbre.attack);
    env.gain.exponentialRampToValueAtTime(0.0001, at + timbre.attack + partialDecay);

    osc.connect(env);
    env.connect(tone);
    osc.start(at);
    osc.stop(at + timbre.attack + partialDecay + 0.05);
  }
}

/**
 * Key moments: a struck bell rather than an arpeggio. Inharmonic partials with
 * staggered decays give it the shimmer a two-note figure can't, and it rings
 * long enough to cover the hold without needing a second gesture.
 */
function scheduleBell(
  ctx: AnyContext,
  dest: AudioNode,
  at: number,
  isPhoto: boolean,
  rootHz: number = ROOT_HZ,
): void {
  // An octave over the chord's root, or its fifth — either way inside the
  // harmony the pad is holding at that moment.
  const fundamental = isPhoto ? rootHz * 2 : rootHz * semitones(7);
  const partials: [number, number, number][] = isPhoto
    ? [
        [1, 0.09, 2.0],
        [2.01, 0.045, 1.5],
        [3.02, 0.026, 1.1],
        [4.16, 0.014, 0.7],
      ]
    : [
        [1, 0.1, 2.2],
        [2.01, 0.04, 1.6],
        [2.99, 0.02, 1.0],
      ];

  const panner = ctx.createStereoPanner();
  panner.pan.value = 0;
  panner.connect(dest);

  for (const [ratio, peak, decay] of partials) {
    const osc = ctx.createOscillator();
    osc.type = "sine";
    osc.frequency.value = fundamental * ratio;
    const env = ctx.createGain();
    env.gain.setValueAtTime(0.0001, at);
    env.gain.linearRampToValueAtTime(peak, at + 0.02);
    env.gain.exponentialRampToValueAtTime(0.0001, at + decay);
    osc.connect(env);
    env.connect(panner);
    osc.start(at);
    osc.stop(at + decay + 0.05);
  }
}

/**
 * The week's last breath: the pad's own chord, swelled slowly and left to
 * decay, with one bell on top. A resolution, not a fanfare — the replay is
 * reporting, and it should sound like it finished rather than like it won.
 */
function scheduleClose(ctx: AnyContext, dest: AudioNode, at: number): void {
  // Resolves on the tonic whatever chord the week ended on, so the piece lands.
  const chord = [
    PAD_ROOT_HZ,
    PAD_ROOT_HZ * semitones(7),
    ROOT_HZ * semitones(3),
    ROOT_HZ * 2,
  ];
  chord.forEach((freqHz, index) => {
    const osc = ctx.createOscillator();
    osc.type = index === 0 ? "triangle" : "sine";
    osc.frequency.value = freqHz;
    const env = ctx.createGain();
    const start = at + index * 0.06;
    env.gain.setValueAtTime(0.0001, start);
    env.gain.linearRampToValueAtTime(0.05, start + 0.5);
    env.gain.exponentialRampToValueAtTime(0.0001, start + 3.2);
    osc.connect(env);
    env.connect(dest);
    osc.start(start);
    osc.stop(start + 3.3);
  });
  scheduleBell(ctx, dest, at + 0.18, false);
}

// ── Pad ─────────────────────────────────────────────────────────────────────

/** Matches the bracket loader's 4s breathe (see Loader.css). */
const BREATH_HZ = 0.25;
const BREATH_DEPTH = 0.22;

interface PadBundle {
  sources: AudioScheduledSourceNode[];
  nodes: AudioNode[];
  gain: GainNode;
}

/**
 * The bed: a quiet pedal tone on the root and its fifth, and nothing else.
 *
 * Deliberately plain. The earlier version carried a sawtooth voice and two
 * triangles detuned against each other, under a filter that swept most of an
 * octave with the day/night clock and retuned on every chord — four separate
 * sources of the buzz and wobble that made it grating rather than ambient.
 * Pure sines cannot be harsh, a pedal tone stays consonant under all four
 * chords of the progression (they are all drawn from one mode), and day only
 * nudges the level and the brightness now instead of sweeping them.
 *
 * Level and filter are still ramped between sample points rather than stepped,
 * which is the difference between dusk arriving and the pad glitching, and it
 * still breathes on the loader's 4-second cycle.
 */
function schedulePad(
  ctx: AnyContext,
  dest: AudioNode,
  schedule: AudioSchedule,
  opts: { audioOrigin: number; playOrigin: number; endSec: number },
): PadBundle {
  const { audioOrigin, playOrigin, endSec } = opts;

  const filter = ctx.createBiquadFilter();
  filter.type = "lowpass";
  filter.Q.value = 0.8;

  const gain = ctx.createGain();
  filter.connect(gain);
  gain.connect(dest);

  // Kept well under the voices: this is the room the week happens in, and it
  // should never be the loudest thing playing. Daylight opens it a little and
  // lifts it a little — enough to notice across a whole day, not enough to
  // hear as a filter moving.
  const levelAt = (pt: AudioPadPoint) => ({
    cutoff: 300 + (1 - pt.nightLevel) * 220 + pt.weekendLevel * 60,
    level: 0.013 + (1 - pt.nightLevel) * 0.005 + pt.weekendLevel * 0.004,
  });

  // Seed from the sample covering the start position, then ramp through the rest.
  const startPoint =
    [...schedule.padPoints].reverse().find((pt) => pt.playMs <= playOrigin) ??
    schedule.padPoints[0];
  if (startPoint) {
    const seed = levelAt(startPoint);
    filter.frequency.setValueAtTime(seed.cutoff, audioOrigin);
    gain.gain.setValueAtTime(seed.level, audioOrigin);
  }
  for (const pt of schedule.padPoints) {
    if (pt.playMs <= playOrigin) continue;
    const at = audioOrigin + (pt.playMs - playOrigin) / 1000;
    const { cutoff, level } = levelAt(pt);
    filter.frequency.linearRampToValueAtTime(cutoff, at);
    gain.gain.linearRampToValueAtTime(level, at);
  }

  const breath = ctx.createOscillator();
  breath.type = "sine";
  breath.frequency.value = BREATH_HZ;
  const breathDepth = ctx.createGain();
  // Scaled off the pad's own level so the breath stays proportional.
  breathDepth.gain.value = 0.013 * BREATH_DEPTH;
  breath.connect(breathDepth);
  breathDepth.connect(gain.gain);
  breath.start(audioOrigin);
  breath.stop(endSec);

  // A pedal tone: root, fifth, and a whisper of the octave. Fixed, so the
  // harmony turns in the notes above it rather than dragging the floor around.
  const voices: [number, number][] = [
    [1, 1],
    [semitones(7), 0.4],
    [2, 0.12],
  ];

  const sources: AudioScheduledSourceNode[] = [breath];
  const nodes: AudioNode[] = [filter, gain, breathDepth];
  for (const [ratio, mix] of voices) {
    const osc = ctx.createOscillator();
    osc.type = "sine";
    osc.frequency.value = PAD_ROOT_HZ * ratio;
    const voiceGain = ctx.createGain();
    voiceGain.gain.value = mix;
    osc.connect(voiceGain);
    voiceGain.connect(filter);
    osc.start(audioOrigin);
    osc.stop(endSec);
    sources.push(osc);
    nodes.push(voiceGain);
  }

  return { sources, nodes, gain };
}

// ── Live engine ─────────────────────────────────────────────────────────────

const MASTER_LEVEL = 0.9;
/** How far ahead of the playhead notes are handed to the context. */
const LOOKAHEAD_MS = 700;
/** How often the scheduler wakes up to top up that window. */
const SCHEDULER_TICK_MS = 120;
/** Fade applied on pause and seek, so stopping never clicks. */
const FADE_SECONDS = 0.09;

/**
 * Create a live audio engine for the replay.
 *
 * Notes are scheduled in a rolling window rather than all at once: a busy week
 * is hundreds of events, and handing the graph every voice up front costs a
 * visible hitch at the moment playback starts — exactly when the animation
 * needs the main thread.
 */
export function createReplayAudioEngine(schedule: AudioSchedule): ReplayAudioEngine {
  let ctx: AudioContext | null = null;
  let bus: Bus | null = null;
  /** Disposable gain carrying the current run's voices. */
  let generation: GainNode | null = null;
  let pad: PadBundle | null = null;
  let timer: number | null = null;
  let muted = false;

  /** Context time that playback position `playOrigin` maps to. */
  let audioOrigin = 0;
  let playOrigin = 0;
  let nextTick = 0;
  let nextChime = 0;
  let closeScheduled = false;

  const detune = mulberry32(0xc1c1c);

  function ensureContext(): AudioContext {
    if (!ctx) {
      ctx = new AudioContext();
      bus = createBus(ctx, muted ? 0 : MASTER_LEVEL);
    }
    if (ctx.state === "suspended") ctx.resume().catch(() => undefined);
    return ctx;
  }

  /** Fade a node out over FADE_SECONDS, then drop it from the graph. */
  function retire(node: GainNode, atTime: number): void {
    try {
      node.gain.cancelScheduledValues(atTime);
      node.gain.setValueAtTime(node.gain.value, atTime);
      node.gain.linearRampToValueAtTime(0.0001, atTime + FADE_SECONDS);
    } catch {
      // Param already detached; the disconnect below still cleans up.
    }
    window.setTimeout(
      () => {
        try {
          node.disconnect();
        } catch {
          // Already disconnected.
        }
      },
      FADE_SECONDS * 1000 + 400,
    );
  }

  /**
   * Silence the current run.
   *
   * A voice can't be recalled once it is handed to the context, so instead of
   * chasing individual oscillators the whole generation is faded out and
   * abandoned; its notes finish playing into a muted node and stop themselves.
   * The fade is short but not instant, because an abrupt gain cut is itself an
   * audible click.
   */
  function stopSounding(): void {
    if (!ctx) return;
    const now = ctx.currentTime;

    if (generation) {
      retire(generation, now);
      generation = null;
    }
    if (pad) {
      const dying = pad;
      pad = null;
      retire(dying.gain, now);
      for (const source of dying.sources) {
        try {
          source.stop(now + FADE_SECONDS * 2);
        } catch {
          // Already stopped.
        }
      }
    }
  }

  function schedulePending(): void {
    if (!ctx || !generation) return;
    const horizonPlayMs =
      (ctx.currentTime - audioOrigin) * 1000 + playOrigin + LOOKAHEAD_MS;

    while (nextTick < schedule.ticks.length) {
      const tick = schedule.ticks[nextTick];
      if (tick.playMs > horizonPlayMs) break;
      const at = audioOrigin + (tick.playMs - playOrigin) / 1000;
      if (at >= ctx.currentTime) {
        scheduleVoice(
          ctx,
          generation,
          at,
          tick.freqHz,
          tick.panX,
          tick.level,
          TIMBRES[tick.timbre % TIMBRES.length],
          (detune() - 0.5) * 0.006,
        );
      }
      nextTick++;
    }

    while (nextChime < schedule.chimes.length) {
      const chime = schedule.chimes[nextChime];
      if (chime.playMs > horizonPlayMs) break;
      const at = audioOrigin + (chime.playMs - playOrigin) / 1000;
      if (at >= ctx.currentTime) {
        scheduleBell(ctx, generation, at, chime.isPhoto, chime.rootHz);
      }
      nextChime++;
    }

    if (!closeScheduled && schedule.endMs <= horizonPlayMs) {
      const at = audioOrigin + (schedule.endMs - playOrigin) / 1000;
      if (at >= ctx.currentTime) scheduleClose(ctx, generation, at);
      closeScheduled = true;
      // Nothing left to schedule; the tail rings out on its own.
      stopTimer();
    }
  }

  function startTimer(): void {
    if (timer != null) return;
    timer = window.setInterval(schedulePending, SCHEDULER_TICK_MS);
  }

  function stopTimer(): void {
    if (timer == null) return;
    window.clearInterval(timer);
    timer = null;
  }

  function beginAt(atPlayMs: number): void {
    const context = ensureContext();
    if (!bus) return;
    stopSounding();

    audioOrigin = context.currentTime + 0.06;
    playOrigin = atPlayMs;
    nextTick = schedule.ticks.findIndex((t) => t.playMs >= atPlayMs);
    if (nextTick < 0) nextTick = schedule.ticks.length;
    nextChime = schedule.chimes.findIndex((c) => c.playMs >= atPlayMs);
    if (nextChime < 0) nextChime = schedule.chimes.length;
    closeScheduled = schedule.endMs < atPlayMs;

    generation = context.createGain();
    generation.gain.value = 1;
    generation.connect(bus.voiceIn);

    const remainingSec = Math.max(0, (schedule.endMs - atPlayMs) / 1000);
    pad = schedulePad(context, bus.pad, schedule, {
      audioOrigin,
      playOrigin,
      endSec: audioOrigin + remainingSec + 4,
    });

    schedulePending();
    startTimer();
  }

  return {
    start(atPlayMs = 0) {
      beginAt(atPlayMs);
    },

    pause() {
      stopTimer();
      stopSounding();
    },

    seek(playMs) {
      if (!ctx) return;
      beginAt(playMs);
    },

    setMuted(next) {
      muted = next;
      if (bus && ctx) {
        bus.master.gain.setTargetAtTime(
          next ? 0 : MASTER_LEVEL,
          ctx.currentTime,
          0.05,
        );
      }
    },

    dispose() {
      stopTimer();
      stopSounding();
      ctx?.close().catch(() => undefined);
      ctx = null;
      bus = null;
      generation = null;
    },
  };
}

// ── Offline render (video export) ───────────────────────────────────────────

/** Sample rate of the exported audio track (AAC-friendly). */
const OFFLINE_SAMPLE_RATE = 44100;
/** Default room for the closing swell to decay into. */
const OFFLINE_TAIL_MS = 3400;

/**
 * Render the whole schedule to an AudioBuffer with no AudioContext and no user
 * gesture, for muxing into the exported video.
 *
 * @param durationMs Playback duration; the closing swell starts here.
 * @param tailMs     Room after it. The caller sets this to the video's outro
 *   length so the two tracks end together — a track that outlives the last
 *   frame makes players hold a frozen image at the end of the clip. The
 *   closing swell is far below audible by then, so trimming it is free.
 */
export async function renderReplayAudio(
  schedule: AudioSchedule,
  durationMs: number,
  tailMs: number = OFFLINE_TAIL_MS,
): Promise<AudioBuffer> {
  const totalMs = durationMs + Math.max(600, tailMs);
  const totalSamples = Math.ceil((OFFLINE_SAMPLE_RATE * totalMs) / 1000);
  const ctx = new OfflineAudioContext(2, totalSamples, OFFLINE_SAMPLE_RATE);
  const bus = createBus(ctx, MASTER_LEVEL);
  const endSec = totalSamples / OFFLINE_SAMPLE_RATE;

  const detune = mulberry32(0xa11ce);
  for (const tick of schedule.ticks) {
    scheduleVoice(
      ctx,
      bus.voiceIn,
      tick.playMs / 1000,
      tick.freqHz,
      tick.panX,
      tick.level,
      TIMBRES[tick.timbre % TIMBRES.length],
      (detune() - 0.5) * 0.006,
    );
  }
  for (const chime of schedule.chimes) {
    scheduleBell(
      ctx,
      bus.voiceIn,
      chime.playMs / 1000,
      chime.isPhoto,
      chime.rootHz,
    );
  }
  scheduleClose(ctx, bus.voiceIn, durationMs / 1000);
  schedulePad(ctx, bus.pad, schedule, {
    audioOrigin: 0,
    playOrigin: 0,
    endSec,
  });

  return await ctx.startRendering();
}
