"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useAuth0 } from "@auth0/auth0-react";
import {
  InboxDetailResponse,
  InboxItem,
  getInboxItem,
  markInboxRead,
} from "@/lib/apiClient";
import { recordProductEvent } from "@/lib/productAnalytics";
import { trackInboxItemBack, trackInboxItemOpened } from "@/lib/analytics";
import "@/app/newsletter-inline-theme.css";
import styles from "./Inbox.module.css";

// ---------------------------------------------------------------------------
// Back chevron icon
// ---------------------------------------------------------------------------

function ChevronLeftIcon({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <polyline points="15 18 9 12 15 6" />
    </svg>
  );
}

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface InboxItemViewProps {
  id: string;
  /** The list item we already have (used for initial state + tracking). */
  cachedItem?: InboxItem;
  onBack: () => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function InboxItemView({
  id,
  cachedItem,
  onBack,
}: InboxItemViewProps) {
  const { getAccessTokenSilently } = useAuth0();
  const [detail, setDetail] = useState<InboxDetailResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const openedAtMs = useRef(Date.now());

  useEffect(() => {
    if (!id) return;
    setLoading(true);
    openedAtMs.current = Date.now();

    getAccessTokenSilently()
      .then((token) =>
        Promise.all([
          getInboxItem(token, id),
          markInboxRead(token, id).catch(() => null),
        ])
      )
      .then(([data]: [InboxDetailResponse, unknown]) => {
        setDetail(data);

        // Track item opened
        recordProductEvent("inbox_item_opened", {
          item_id: id,
          item_type: data.type,
          scope: cachedItem?.scope ?? "city",
          is_private: cachedItem?.is_private ?? false,
          city_slug: data.city_slug,
          was_unread: cachedItem ? !cachedItem.is_read : false,
          days_since_sent: data.sent_at
            ? Math.floor(
                (Date.now() - new Date(data.sent_at).getTime()) / 86_400_000
              )
            : 0,
        });
        trackInboxItemOpened({
          item_id: id,
          item_type: data.type,
          scope: cachedItem?.scope ?? "city",
          is_private: cachedItem?.is_private ?? false,
          city_slug: data.city_slug,
          was_unread: cachedItem ? !cachedItem.is_read : false,
        });
      })
      .catch((err) => {
        const msg = err instanceof Error ? err.message : "Unknown error";
        setError(msg);
        recordProductEvent("inbox_load_failed", { phase: "detail", status: "network" });
      })
      .finally(() => setLoading(false));
  }, [id, getAccessTokenSilently, cachedItem]);

  const handleBack = useCallback(() => {
    const timeInDetail = Date.now() - openedAtMs.current;
    recordProductEvent("inbox_item_back", {
      item_id: id,
      item_type: detail?.type ?? "edition",
      time_in_detail_ms: timeInDetail,
    });
    trackInboxItemBack({
      item_id: id,
      item_type: detail?.type ?? "edition",
      time_in_detail_ms: timeInDetail,
    });
    onBack();
  }, [id, detail, onBack]);

  return (
    <div className={styles.detail}>
      {/* Sticky header with back button */}
      <div className={styles.detailHeader}>
        <button
          type="button"
          className={styles.backButton}
          onClick={handleBack}
          aria-label="Back to Inbox"
        >
          <ChevronLeftIcon className={styles.backIcon} />
          Back to Inbox
        </button>
      </div>

      {/* Body */}
      <div className={styles.detailBody}>
        {loading && (
          <div className={styles.centeredState}>
            <div className="tc-loader" data-size="md" />
          </div>
        )}

        {!loading && error && (
          <div className={styles.centeredState}>
            <p className={styles.emptyText}>
              Could not load this newsletter. Please go back and try again.
            </p>
          </div>
        )}

        {!loading && !error && detail && (
          <>
            <div
              className={`${styles.detailBodyHtml} newsletter-inline-theme`}
              // Newsletter body HTML is generated by the platform pipeline
              // eslint-disable-next-line react/no-danger
              dangerouslySetInnerHTML={{ __html: detail.body_html }}
            />
            {detail.public_url && (
              <a
                href={detail.public_url}
                target="_blank"
                rel="noopener noreferrer"
                className={styles.detailPublicLink}
              >
                View on web
              </a>
            )}
          </>
        )}
      </div>
    </div>
  );
}
