// Generated by transparentcity-platform scripts/analysis/flock/report/export_ui_bundle.py.
// Pinned results for /reports/flock. Do not edit by hand.

export const FLOCK_DATA = {
  "generated_from": {
    "retrieved_utc": "2026-08-30T04:46:11.700251+00:00",
    "panel": [
      "2022-01",
      "2026-06"
    ],
    "preregistration_commit": "f093c5df"
  },
  "payments": {
    "sf_total_paid": 5191350.0,
    "sf_by_fy": {
      "2024": 1535000.0,
      "2025": 21600.0,
      "2026": 2434750.0,
      "2027": 1200000.0
    },
    "sf_contracts": [
      {
        "title": "POL - ALPR subscription",
        "agreed": 3935000.0,
        "paid": 3935000.0,
        "start": "2024-02-20",
        "end": "2027-02-19"
      },
      {
        "title": "POL- Flock Aerodome DFR",
        "agreed": 2484532.0,
        "paid": 1228000.0,
        "start": "2025-09-22",
        "end": "2027-09-21"
      }
    ],
    "denver_total": 179909.35,
    "denver_rows": [
      {
        "date": "2025-10-15",
        "amount": 130009.35
      },
      {
        "date": "2025-12-12",
        "amount": 43000.0
      },
      {
        "date": "2025-12-12",
        "amount": 1000.0
      },
      {
        "date": "2025-12-12",
        "amount": 2500.0
      },
      {
        "date": "2025-12-12",
        "amount": 900.0
      },
      {
        "date": "2025-12-12",
        "amount": 2500.0
      }
    ],
    "chicago_flock_rows": 0
  },
  "s2": {
    "sf": {
      "on": {
        "pre_mean": 744.1,
        "post_mean": 375.7,
        "post_months_used": 12,
        "pct_change": -49.5,
        "controls_pct_change": {
          "chicago": -36.6,
          "nyc": -12.6,
          "seattle": -34.6
        }
      }
    },
    "oakland": {
      "on": {
        "pre_mean": 944.4,
        "post_mean": 548.7,
        "post_months_used": 12,
        "pct_change": -41.9,
        "controls_pct_change": {
          "chicago": -36.6,
          "nyc": -12.6,
          "seattle": -34.6
        }
      }
    },
    "austin": {
      "on": {
        "pre_mean": 577.2,
        "post_mean": 370.2,
        "post_months_used": 12,
        "pct_change": -35.9,
        "controls_pct_change": {
          "chicago": -36.4,
          "nyc": -12.1,
          "seattle": -30.8
        }
      },
      "off": {
        "pre_mean": 388.8,
        "post_mean": 304.2,
        "post_months_used": 12,
        "pct_change": -21.8,
        "controls_pct_change": {
          "chicago": -3.1,
          "nyc": -9.1,
          "seattle": -17.6
        }
      }
    },
    "denver": {
      "on": {
        "pre_mean": 942.3,
        "post_mean": 505.9,
        "post_months_used": 12,
        "pct_change": -46.3,
        "controls_pct_change": {
          "chicago": -36.6,
          "nyc": -12.6,
          "seattle": -34.6
        }
      },
      "off": {
        "pre_mean": 429.2,
        "post_mean": 356.3,
        "post_months_used": 3,
        "pct_change": -17.0,
        "controls_pct_change": {
          "chicago": 6.9,
          "nyc": -8.8,
          "seattle": -19.7
        }
      }
    }
  },
  "s3": {
    "primary": {
      "beta": -0.2007,
      "se_cluster": 0.1153,
      "pct_effect": -18.2,
      "n_permutations": 840,
      "perm_p_two_sided": 0.1571
    },
    "levels": -53.46626984127009,
    "sf_on_2024_07": {
      "beta": -0.1916,
      "se_cluster": 0.1122,
      "pct_effect": -17.4,
      "n_permutations": 840,
      "perm_p_two_sided": 0.1476
    },
    "excl_austin": {
      "beta": -0.3069,
      "se_cluster": 0.0993,
      "pct_effect": -26.4,
      "n_permutations": 360,
      "perm_p_two_sided": 0.0167
    },
    "excl_denver": {
      "beta": -0.1533,
      "se_cluster": 0.1348,
      "pct_effect": -14.2,
      "n_permutations": 360,
      "perm_p_two_sided": 0.1833
    },
    "winsorized": {
      "beta": -0.2027,
      "se_cluster": 0.1162,
      "pct_effect": -18.3,
      "n_permutations": 840,
      "perm_p_two_sided": 0.1476
    },
    "levels_note": "coefficient in thefts per month, OLS with city and month fixed effects"
  },
  "annual": {
    "sf": {
      "2022": 8225,
      "2023": 8985,
      "2024": 7252,
      "2025": 4143
    },
    "oakland": {
      "2022": 8431,
      "2023": 11271,
      "2024": 9234,
      "2025": 6219
    },
    "denver": {
      "2022": 15005,
      "2023": 12249,
      "2024": 8723,
      "2025": 5575
    },
    "austin": {
      "2022": 5102,
      "2023": 6790,
      "2024": 5829,
      "2025": 4269
    },
    "chicago": {
      "2022": 21474,
      "2023": 29257,
      "2024": 21713,
      "2025": 17253
    },
    "nyc": {
      "2022": 13791,
      "2023": 15780,
      "2024": 14166,
      "2025": 13366
    },
    "seattle": {
      "2022": 6978,
      "2023": 9259,
      "2024": 7439,
      "2025": 5799
    }
  },
  "austin_clean_window": {
    "austin": {
      "pre_mean": 388.8,
      "post_mean": 339.3,
      "pct": -12.7
    },
    "chicago": {
      "pre_mean": 1559.2,
      "post_mean": 1506.7,
      "pct": -3.4
    },
    "nyc": {
      "pre_mean": 1156.2,
      "post_mean": 1106.9,
      "pct": -4.3
    },
    "seattle": {
      "pre_mean": 543.8,
      "post_mean": 505.9,
      "pct": -7.0
    }
  },
  "block": {
    "cameras": 333,
    "incidents_no_geo": 390,
    "near": {
      "before": 3508,
      "after": 3046,
      "monthly_rate_before": 292.3,
      "monthly_rate_after": 145.0,
      "pct": -50.4
    },
    "far": {
      "before": 1934,
      "after": 1404,
      "monthly_rate_before": 161.2,
      "monthly_rate_after": 66.9,
      "pct": -58.5
    },
    "neighborhoods": [
      {
        "name": "Bayview Hunters Point",
        "y2023": 1025,
        "y2025": 497,
        "pct": -51.5
      },
      {
        "name": "Mission",
        "y2023": 941,
        "y2025": 462,
        "pct": -50.9
      },
      {
        "name": "South of Market",
        "y2023": 538,
        "y2025": 298,
        "pct": -44.6
      },
      {
        "name": "Tenderloin",
        "y2023": 438,
        "y2025": 274,
        "pct": -37.4
      },
      {
        "name": "Sunset/Parkside",
        "y2023": 389,
        "y2025": 135,
        "pct": -65.3
      },
      {
        "name": "Bernal Heights",
        "y2023": 378,
        "y2025": 127,
        "pct": -66.4
      },
      {
        "name": "Excelsior",
        "y2023": 334,
        "y2025": 152,
        "pct": -54.5
      },
      {
        "name": "Western Addition",
        "y2023": 297,
        "y2025": 141,
        "pct": -52.5
      },
      {
        "name": "West of Twin Peaks",
        "y2023": 291,
        "y2025": 91,
        "pct": -68.7
      },
      {
        "name": "Financial District/South Beach",
        "y2023": 281,
        "y2025": 176,
        "pct": -37.4
      },
      {
        "name": "Potrero Hill",
        "y2023": 260,
        "y2025": 92,
        "pct": -64.6
      },
      {
        "name": "Portola",
        "y2023": 259,
        "y2025": 91,
        "pct": -64.9
      },
      {
        "name": "Nob Hill",
        "y2023": 240,
        "y2025": 109,
        "pct": -54.6
      },
      {
        "name": "Outer Mission",
        "y2023": 234,
        "y2025": 99,
        "pct": -57.7
      },
      {
        "name": "Hayes Valley",
        "y2023": 226,
        "y2025": 106,
        "pct": -53.1
      },
      {
        "name": "Castro/Upper Market",
        "y2023": 216,
        "y2025": 103,
        "pct": -52.3
      },
      {
        "name": "Oceanview/Merced/Ingleside",
        "y2023": 209,
        "y2025": 95,
        "pct": -54.5
      },
      {
        "name": "Visitacion Valley",
        "y2023": 201,
        "y2025": 66,
        "pct": -67.2
      }
    ]
  },
  "s2_no_ramp": {
    "sf": {
      "pre_mean": 744.1,
      "post_mean": 517.7,
      "pct_change": -30.4,
      "controls_pct_change": {
        "chicago": -28.5,
        "nyc": -10.2,
        "seattle": -28.3
      }
    },
    "oakland": {
      "pre_mean": 944.4,
      "post_mean": 662.1,
      "pct_change": -29.9,
      "controls_pct_change": {
        "chicago": -28.5,
        "nyc": -10.2,
        "seattle": -28.3
      }
    },
    "austin": {
      "pre_mean": 577.2,
      "post_mean": 454.1,
      "pct_change": -21.3,
      "controls_pct_change": {
        "chicago": -27.1,
        "nyc": -12.1,
        "seattle": -23.8
      }
    },
    "denver": {
      "pre_mean": 942.3,
      "post_mean": 643.1,
      "pct_change": -31.8,
      "controls_pct_change": {
        "chicago": -28.5,
        "nyc": -10.2,
        "seattle": -28.3
      }
    }
  },
  "denver_on_sensitivity": {
    "2024-02": {
      "s2_pct_change": -43.4,
      "s2_controls": {
        "chicago": -36.4,
        "nyc": -12.1,
        "seattle": -30.8
      },
      "s3_pct_effect": -18.8,
      "s3_perm_p": 0.1286
    },
    "2024-06": {
      "s2_pct_change": -48.8,
      "s2_controls": {
        "chicago": -34.2,
        "nyc": -11.8,
        "seattle": -37.1
      },
      "s3_pct_effect": -17.2,
      "s3_perm_p": 0.169
    }
  },
  "austin_on_sensitivity": {
    "2024-04": {
      "s2_pct_change": -38.6,
      "s2_controls": {
        "chicago": -36.6,
        "nyc": -12.6,
        "seattle": -34.6
      }
    }
  },
  "populations": {
    "sf": 808988,
    "oakland": 436504,
    "austin": 979882,
    "denver": 716577,
    "chicago": 2664452,
    "nyc": 8258035,
    "seattle": 755078
  }
} as const;
